version: 2.1

executors:
  powershell-executor:
    docker:
      - image: mcr.microsoft.com/powershell:lts

jobs:
  build:
    executor: powershell-executor
    steps:
      - checkout

      - run:
          name: Print Environment Variable
          command: |
            pwsh -Command '
              $envVarValue = $args[0]
              Write-Output "Pipeline_BreakBuildWhenVulnsFound: $envVarValue"
            '
            arguments:
              - $Pipeline_BreakBuildWhenVulnsFound
          no_output_timeout: 10m

workflows:
  version: 2
  build_workflow:
    jobs:
      - build
