version: 2.1

executors:
  powershell-executor:
    docker:
      - image: mcr.microsoft.com/powershell:lts

jobs:
  build:
    executor: powershell-executor
    steps:
      - checkout

      - run:
          name: zipRepo
          command: |
            pwsh -Command '
              Write-Host "sourcePath=${env:CIRCLE_JOB}"
              Write-Host "sourcePath=${env:Offensive360SastUi_BaseUrl}"
              
              Write-Output "sourcePath=${env:CIRCLE_JOB}"
              Write-Output "sourcePath=${env:Offensive360SastUi_BaseUrl}"
              
              echo "sourcePath=${env:CIRCLE_JOB}"
              echo "sourcePath=${env:Offensive360SastUi_BaseUrl}"
              
              Write-Host "sourcePath=$env:CIRCLE_JOB"
              Write-Host "sourcePath=$env:Offensive360SastUi_BaseUrl"
              
              Write-Output "sourcePath=$env:CIRCLE_JOB"
              Write-Output "sourcePath=$env:Offensive360SastUi_BaseUrl"
              
              echo "sourcePath=$env:CIRCLE_JOB"
              echo "sourcePath=$env:Offensive360SastUi_BaseUrl"
            '

workflows:
  version: 2
  build_workflow:
    jobs:
      - build
