version: 2.1

executors:
  powershell-executor:
    docker:
      - image: mcr.microsoft.com/powershell:lts

jobs:
  build:
    executor: powershell-executor
    steps:
      - checkout

      - run:
          name: Print Environment Variable
          command: |
            pwsh -Command '
              Write-Output "$Pipeline_BreakBuildWhenVulnsFound"

workflows:
  version: 2
  build_workflow:
    jobs:
      - build
