version: 2.1

executors:
  powershell-executor:
    docker:
      - image: mcr.microsoft.com/powershell:lts

jobs:
  build:
    executor: powershell-executor
    steps:
      - checkout

      - run:
          name: zipRepo
          command: |
            pwsh -Command '
              $sourcePath = "/root/project"
              Write-Host "sourcePath=$sourcePath"
              $destinationPath = $sourcePath #Split-Path -Path "$sourcePath"
              $destinationPath += "\\${env:CIRCLE_JOB}-${env:CIRCLE_BUILD_NUM}.zip"
              Write-Host "destinationPath=$destinationPath"

              if(Test-Path -Path $destinationPath -PathType Leaf)
              {
                  Remove-Item $destinationPath
              }

              Add-Type -Assembly "System.IO.Compression.FileSystem"
              $zip = [System.IO.Compression.ZipFile]::Open($destinationPath, "create")
              $files = [IO.Directory]::GetFiles($sourcePath, "*" , [IO.SearchOption]::AllDirectories)
              foreach($file in $files)
              {
                  $relPath = $file.Substring($sourcePath.Length).TrimStart("\\").TrimStart("/").Replace("\\\\", "/").Replace("\\", "/")
                  $a = [System.IO.Compression.ZipFileExtensions]::CreateEntryFromFile($zip, $file.Replace("\\\\", "/").Replace("\\", "/"), $relPath)
              }
              $zip.Dispose()
            '

workflows:
  version: 2
  build_workflow:
    jobs:
      - build
