version: 2.1

executors:
  powershell-executor:
    docker:
      - image: mcr.microsoft.com/powershell:lts

jobs:
  build:
    executor: powershell-executor
    steps:
      - checkout

      - run:
          name: Run PowerShell script
          command: |
            pwsh -Command '
              $sourcePath = "${env:CIRCLE_WORKING_DIRECTORY}"
              Write-Host "$sourcePath"
            '

workflows:
  version: 2
  build_workflow:
    jobs:
      - build
