version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14

    steps:
      - checkout

      - run:
          name: Print Secret Value
          command: echo "Secret Value: $SECRET_VALUE"
          environment:
            SECRET_VALUE: $SECRET_VALUE
          no_output_timeout: 10m

      - run:
          name: Print Unmasked Secret Value
          command: echo "Unmasked Secret Value: $SECRET_VALUE"
          environment:
            SECRET_VALUE: $SECRET_VALUE
            CIRCLE_UNMASK: true
          no_output_timeout: 10m

workflows:
  version: 2
  build_workflow:
    jobs:
      - build
