version: 2.1

executors:
  powershell-executor:
    docker:
      - image: mcr.microsoft.com/powershell:lts

jobs:
  build:
    executor: powershell-executor
    steps:
      - checkout

      - run:
          name: zipRepo
          environment:
            Offensive360SastUi_BaseUrl: $env:Offensive360SastUi_BaseUrl
            CIRCLE_UNMASK: true
          command: |
            pwsh -Command '
              Write-Host "sourcePath=${env:CIRCLE_JOB}"
              Write-Host "sourcePath=${env:Offensive360SastUi_BaseUrl}"
              Write-Host "sourcePath=${Offensive360SastUi_BaseUrl}"
              Write-Host "sourcePath=$Offensive360SastUi_BaseUrl"
            '

workflows:
  version: 2
  build_workflow:
    jobs:
      - build
