version: 2.1

executors:
  powershell-executor:
    docker:
      - image: mcr.microsoft.com/powershell:lts

jobs:
  build:
    executor: powershell-executor
    steps:
      - checkout

      - run:
          name: Get Custom Environment Variable
          command: |
            pwsh -Command '
              $customVar = $env:Offensive360SastUi_BaseUrl
              Write-Output "Custom Variable: $customVar"
            '
          environment:
            CUSTOM_VARIABLE: $CUSTOM_VARIABLE
          no_output_timeout: 10m

workflows:
  version: 2
  build_workflow:
    jobs:
      - build
