name: Sast Scan Process
 
on:
  push:
    branches: [ master ]

jobs:
  zip-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r vendor.zip vendor
      - uses: actions/upload-artifact@v2
        with:
          name: vendor.zip
