name: Sast Scan Process
 
on:
  push:
    branches: [ master ]

jobs:
  zip-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Printing hello
        shell: pwsh
        run: |
          $sourcePath = "${{ github.workspace }}"
          write-host "$sourcePath"
          $destinationPath = Split-Path -Path "$sourcePath"
          $destinationPath += "\\${{ github.event.repository.name }}-${{ github.run_number }}-${{ github.run_attempt }}.zip"
          Write-Host "$destinationPath"

