name: Sast Scan Process
 
on:
  push:
    branches: [ master ]

jobs:
  zip-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Printing hello
        shell: pwsh
        run: |
          $sourcePath = "${{ github.workspace }}"
          write-host "$sourcePath"
